### ISSUE TITLE
0/0 loading progress

### ISSUE THREAD

**Issue by Alegz333** [fr3fou/discord-mutual-friends#12]
After I input my token using the provided tutorial all I see is loading progress of 0/0. Zero changes.

**Comment by fr3fou** [comment]
hey, once #9 is resolved / better error handling is introduced, we'll be able to debug this. until that's done, mind checking if you pasted the token correctly, e.g no spaces around it or unnecessary characters?

**Comment by fr3fou** [comment]
hey, I made a new release https://github.com/fr3fou/discord-mutual-friends/releases/tag/v2.1.0 which shows an error if you have an invalid token, mind trying again?
