### ISSUE TITLE
Support Discord data export


### ISSUE THREAD

**Issue by couleurm** [fr3fou/discord-mutual-friends#13]
Quote from README:

> Support for reading your relationships from a Discord Data Export
> e.g. you request your data from Discord and you can point this app to your archive/folder. This way you won't be making any HTTP calls nor would this require self botting as the app will have access to your data directly.

Does Discord data export include this data? If so I'll let you guys know once I receive mine and share a few samples if that sort stuff is not already documented

**Comment by couleurm** [comment]
yup, couldn't find anything related to mutual friends :(

ig ill wait till this gets more popular before risking

**Comment by fr3fou** [comment]
damn, that's unfortunate. thanks for checking though!
