### ISSUE TITLE
.exe Release triggers antivirus

### ISSUE THREAD

**Issue by VertyyBird** [fr3fou/discord-mutual-friends#15]
I went to the releases page and downloaded the .exe from there and Windows Defender blocked it. I bypassed it since I figured it was just Defender being a bit paranoid like with other repos, but I put it through VirusTotal and a lot of reliable AVs are flagging it as a trojan.

Link to VT scan: https://www.virustotal.com/gui/file/112dfd495b70fa67948d45f790f8bda5f19a197e88a57a34942f9598ba21e794

**Comment by fr3fou** [comment]
hi! This is a common issue for Wails apps (which is what I use) and in general desktop programs written in Golang:
Here are some posts that have reported the same problems:

- https://github.com/wailsapp/wails/issues/3045
- https://github.com/wailsapp/wails/issues/2965
- https://www.reddit.com/r/golang/comments/1729tuc/my_programs_keep_getting_flagged_as_viruses

Feel free to ignore it or try to compile the application yourself – there are some instructions in the README, but you do need some technical knowledge.
