### ISSUE TITLE
I'd like to use this program but i have no idea how to

### ISSUE THREAD

**Issue by Tiriaa** [fr3fou/discord-mutual-friends#2]
Well i think the title is pretty self explenatory, can i get a little explanation on how to run it please.
Can do it via discord if its easier

**Comment by fr3fou** [comment]
Hey, I agree that it's a bit hard to run right now. I've been meaning to make it a bit more user-friendly, but haven't had the time. Mind if you send your Discord?

**Comment by Tiriaa** [comment]
Kiki~#5282
