### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by SilentTrash** [fr3fou/discord-mutual-friends#3]
It seems like a pretty neat thing to use and I was wondering how to get it working.

**Comment by fr3fou** [comment]
Hey @SilentTrash, @couleurm, I just released a proper Desktop App, you can check the GitHub README for more information

**Comment by couleurm** [comment]
hello, i can't risk my discord account even though this seems very useful and cool, looking forward to using it if it ever gets reputable
