### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Alegz333** [fr3fou/discord-mutual-friends#5]
Im am kinda too dumb to run this thing. Maybe include a better tutorial in Readme? Also I sent you invite on discord

**Comment by fr3fou** [comment]
hi, I built some binaries and created a release – you can download the respective binary for your OS, e.g. on Windows you'd download windows-amd64.exe and launch it.

after you launch it, you have to enter your discord token, here's a guide on how to get it https://www.androidauthority.com/get-discord-token-3149920/

you can get the releases here: https://github.com/fr3fou/discord-mutual-friends/releases

**Comment by fr3fou** [comment]
after you run it, the program will spit out a file that ends with `.dot`, this file itself can be visualised with any graphviz / dot visualiser, e.g. https://gephi.org/ or any other tool you find online when you google "graphviz online".

i'll definitely consider making this an all-in-one desktop app using something like raylib which performs the graph building and the visualisation.

**Comment by fr3fou** [comment]
Hey @Alegz333, I've since released a proper desktop app – you can check the README for more information
