### ISSUE TITLE
Desktop app gets stuck without displaying any results

### ISSUE THREAD

**Issue by Notchie** [fr3fou/discord-mutual-friends#8]
kinda self explanatory, i put my token in and it gets almost all the way through, but it gets stuck on "loading..." at 159/160.

**Comment by fr3fou** [comment]
hey, thanks for the report. I think I know what's happening, publishing a fix right away

**Comment by Notchie** [comment]
awesome! thanks

**Comment by fr3fou** [comment]
Can you try the https://github.com/fr3fou/discord-mutual-friends/releases/tag/v2.0.1 release?

**Comment by Notchie** [comment]
just did it it works great now!, thanks!
