### ISSUE TITLE
Provide clear indication when can't connect/token isn't valid

### ISSUE THREAD

**Issue by Kyrela** [fr3fou/discord-mutual-friends#9]
# How to reproduce
- Launch the desktop version (Tested on Win11 x64)
- Enter an invalid token (such as 1234)
- Click on `Start`

# Expected behavior

The application displays an error message, such as `Can't connect to Discord. Please make sure you entered a valid token`.

# Actual behavior

The application is stuck on the "Loading" page, constantly displaying `0/0`

**Comment by fr3fou** [comment]
should be resolved now
